# Generated by Django 4.2.20 on 2025-10-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paginas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="bots_imagens/"),
        ),
    ]
